public class TestWIP {
    public static void printWIPMessage(){  
        System.debug('Subha Test on Wednesday for Clean PR');
        System.debug('Subha Test on Friday');
        System.debug('Subha testing Friday Advance');
        System.debug('Subha ET');
        
    }
    
    public static void function3(){
        System.debug('Hello 3');
    }
    
    public static void anotherFunction() {
        // Placeholder
        System.debug('Hi 22nd July');
    }

    public static void anotherFunctionInMain(){
        System.debug('This is a change directly in main branch');
    }

    public static void testfunctionforCleanPrOne(){
        System.debug('this is cli clean pr function one');
    }

    public static void testfunctionforCleanPrTwo(){
        System.debug('this is cli clean pr function two');
    }
}
