Public with sharing Class TestConflictResolutionMessageFour {
    public static void printName(){
        System.debug('TestConflictResolutionMessageFour, I added a new line for conflict in dev');
        System.debug('TestConflictResolutionMessageFour 7th July');
        System.debug('I am testing conflict resolution message');
        System.debug('Testing custom suffix commit message');
    }
}