public class TestCleanPR {

    public static void printWIPMessage(){
        System.debug('Subha Test Clean PR modified on tuesday');
        System.debug('Subha Test Clean PR');
        System.debug('Subha testing Monday Clean PR');
        System.debug('Subha Clean PR');
        
    }
    
    public static void anotherFunction() {
        // Placeholder
    }

    public static void cleanPrFunction() {
        // Placeholder
        System.debug('This is a direct commit in the main branch to test clean PR via CLI');
    }

    public static void anotherCleanPrFunction(){
         System.debug('This is another 2 direct commit in the main branch to test clean PR via CLI');
    }
}
