public class TestCleanPR {

    public static void printWIPMessage(){  
        System.debug('Subha Test Clean PR');//I have modified this line to create conflict
        System.debug('Subha testing Monday Clean PR modified in UAT');
        System.debug('Subha testing Monday Clean PR');
        System.debug('Subha Clean PR');
        
    }
    
    public static void anotherFunction() {
        // Placeholder
    }
}
