Public with sharing Class TestCleanPrWithConflict {
    public static void printNameInCleanPR(){
        System.debug('Wehave changes in the main branch 17th Aug 2026 for TestCleanPrWithConflict');
    }

    public static void printNameInCleanPRInDevCli(){
        System.debug('Wehave changes in the CLI from dev on 17th Aug , this is third commit');
    }

    public static void printNameInCleanPRInDevCli3rd(){
        System.debug('Wehave changes in the CLI from dev on 17th Aug ,this is seventh commit single commit');
    }
}
