public class TestWIP {
    public static void printWIPMessage(){  
        System.debug('dev1 dev1 dev1 dev1 miguel miguel miguel subha subha subha');
    }
    
    public static void anotherFunction() {
        // Placeholder
    }

    public static void anotherFunctionInMain(){
        System.debug('This is a change directly in main branch');
    }

    public static void myFirstFunctionForCleanPR(){
        System.debug('this is first function');
    }

    public static void mysecondFunctionForCleanPR(){
        System.debug('this is second function');
    }

    public static void myThirdFunctionForCleanPR(){
        System.debug('this is third function');
    }

    public static void myFourthFunctionForCleanPR(){
        System.debug('this is fourth function');
    }

    public static void myFifthFunctionForCleanPR(){
    System.debug('this is fifth function');
    }

    public static void mySixthFunctionForCleanPR(){
        System.debug('this is sixth function');
    }

    public static void mySeventhFunctionForCleanPR(){
        System.debug('this is seventh function');
    }

    public static void myEigthFunctionForCleanPR(){
        System.debug('this is eigth function');
    }
}
