Public with sharing Class TestConflictResolutionMessage {
    public static void printName(){
        System.debug('I added a new line');
        System.debug('I added a new line for conflict in dev');
        System.debug('My name is subha and I modified in dev on 7th July');
        System.debug('I am testing conflict resolution message');
        System.debug('Wehave changes in the main branch 17th Aug 2026 for TestConflictResolutionMessage');
    }
}
