Public with sharing Class TestConflictResolutionMessageFive {
    public static void printName(){
        System.debug('TestConflictResolutionMessageFive, I added a new line for conflict in dev');
        System.debug('TestConflictResolutionMessageFive 7th July');
        System.debug('I am testing conflict resolution message');
        System.debug('Wehave changes in the main branch 17th Aug 2026');
    }
}
